name: ringtone_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter


  just_audio: ^0.9.39
  set_ringtone: ^1.0.0
  permission_handler: ^11.3.1
  flutter_bloc: ^8.1.6
  connectivity_plus: ^6.0.3
  google_mobile_ads: ^5.2.0
  android_intent_plus: ^5.2.2
  flutter_speed_dial: ^7.0.0
  shared_preferences: ^2.3.3
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter:


  uses-material-design: true
  fonts:
    - family: ReadexPro
      fonts:
        - asset: assets/fonts/ReadexPro.ttf
          weight: 700
  assets:
    - assets/sounds/
    - assets/images/
    - assets/languages/
